on:
  push:
    tags:
      - 'v*'

name: Create Release And Upload Assets

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20.2'

      - name: Build Web
        run: |
          cd frontend && npm install && npm run build:pro
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Setup GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          version: latest

      - name: Run GoReleaser
        run: goreleaser release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Assets to GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          body: |
            # 一、安装和升级

            ## 1.1 一键安装
            ```sh
            curl -sSL https://resource.fit2cloud.com/1panel/package/quick_start.sh -o quick_start.sh && sudo bash quick_start.sh
            ```

            ## 1.2 在线升级

            登录 1Panel Web 控制台，在页面右下角点击 **【检查更新】** 进行在线升级。

            >更多信息请查阅在线文档：https://1panel.cn/docs/

            # 二、更新日志

          files: |
            dist/*.tar.gz
            dist/checksums.txt

      # - name: Setup OSSUTIL
      #   uses: yizhoumo/setup-ossutil@v1
      #   with:
      #     endpoint: ${{ secrets.OSS_ENDPOINT }}
      #     access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
      #     access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
      #     ossutil-version: '1.7.14'

      # - name: Upload Assets to OSS
      #   run: ossutil cp -r dist/ oss://resource-fit2cloud-com/1panel/package/stable/${{ github.ref_name }}/release/ --include "*.tar.gz" --include "checksums.txt" --only-current-dir --force
